version: '3'

services:
  mysql:
    image: mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: gear_galaxy_rent_db
      MYSQL_USER: ggr_user
      MYSQL_PASSWORD: ggr_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
